import { REAL_ESTATE } from './real-estate'
import type { IndustryContent } from './types'

/**
 * Industries with a page. An industry is added when someone who knows it has
 * written what the agent asks and does there; a page generated by swapping the
 * industry's name into another's copy is thin, and thin pages cost the rest of
 * the site more than they earn.
 */
export const INDUSTRIES: readonly IndustryContent[] = [REAL_ESTATE]

export function industryPath(industry: IndustryContent): string {
  return `/industries/${industry.slug}/`
}
